export interface Achievement {
  id: number;
  title: string;
  description: string;
  icon: string;
  category: "math" | "sudoku" | "arena" | "general";
  progress: number;
  maxProgress: number;
  isUnlocked: boolean;
  unlockedDate?: string;
  rarity: "common" | "rare" | "epic" | "legendary";
  xpReward: number;
}

export const achievementsData: Achievement[] = [
  {
    id: 1,
    title: "First Steps",
    description: "Complete your first math competition",
    icon: "🏁",
    category: "math",
    progress: 1,
    maxProgress: 1,
    isUnlocked: true,
    unlockedDate: "2024-01-15",
    rarity: "common",
    xpReward: 50,
  },
  {
    id: 2,
    title: "Speed Demon",
    description: "Answer 10 math questions in under 30 seconds",
    icon: "⚡",
    category: "math",
    progress: 7,
    maxProgress: 10,
    isUnlocked: false,
    rarity: "rare",
    xpReward: 150,
  },
  {
    id: 3,
    title: "Sudoku Novice",
    description: "Complete your first Sudoku puzzle",
    icon: "🧩",
    category: "sudoku",
    progress: 1,
    maxProgress: 1,
    isUnlocked: true,
    unlockedDate: "2024-01-20",
    rarity: "common",
    xpReward: 50,
  },
  {
    id: 4,
    title: "Master Solver",
    description: "Complete 50 Sudoku puzzles",
    icon: "🏆",
    category: "sudoku",
    progress: 23,
    maxProgress: 50,
    isUnlocked: false,
    rarity: "epic",
    xpReward: 300,
  },
  {
    id: 5,
    title: "Academic Warrior",
    description: "Win 10 Academic Arena challenges",
    icon: "⚔️",
    category: "arena",
    progress: 4,
    maxProgress: 10,
    isUnlocked: false,
    rarity: "rare",
    xpReward: 200,
  },
  {
    id: 6,
    title: "Perfect Score",
    description: "Score 100% in any competition",
    icon: "💯",
    category: "general",
    progress: 1,
    maxProgress: 1,
    isUnlocked: true,
    unlockedDate: "2024-01-25",
    rarity: "epic",
    xpReward: 250,
  },
  {
    id: 7,
    title: "Dedication",
    description: "Play games for 7 consecutive days",
    icon: "🔥",
    category: "general",
    progress: 5,
    maxProgress: 7,
    isUnlocked: false,
    rarity: "rare",
    xpReward: 180,
  },
  {
    id: 8,
    title: "Gaming Legend",
    description: "Reach level 20 in any game",
    icon: "👑",
    category: "general",
    progress: 15,
    maxProgress: 20,
    isUnlocked: false,
    rarity: "legendary",
    xpReward: 500,
  },
  {
    id: 9,
    title: "Quick Thinker",
    description: "Complete 5 Easy Sudokus in under 3 minutes each",
    icon: "💨",
    category: "sudoku",
    progress: 2,
    maxProgress: 5,
    isUnlocked: false,
    rarity: "rare",
    xpReward: 120,
  },
  {
    id: 10,
    title: "Math Genius",
    description: "Answer 100 math questions correctly",
    icon: "🧠",
    category: "math",
    progress: 67,
    maxProgress: 100,
    isUnlocked: false,
    rarity: "epic",
    xpReward: 280,
  },
];
